[[pre-release-replacements]]
file = "../juniper_actix/Cargo.toml"
exactly = 1
search = "coasys_juniper_graphql_transport_ws = \\{ version = \"[^\"]+\""
replace = "coasys_juniper_graphql_transport_ws = { version = \"{{version}}\""

[[pre-release-replacements]]
file = "../juniper_warp/Cargo.toml"
exactly = 1
search = "coasys_juniper_graphql_transport_ws = \\{ version = \"[^\"]+\""
replace = "coasys_juniper_graphql_transport_ws = { version = \"{{version}}\""