[package]
name = "coasys_juniper_benchmarks"
version = "0.0.0"
edition = "2021"
authors = ["Christoph Herzog <chris@theduke.at>"]
publish = false

[dependencies]
dataloader = "0.17" # for Book only
futures = "0.3"
coasys_juniper = { path = "../juniper" }

[dev-dependencies]
criterion = "0.5"
tokio = { version = "1.0", features = ["rt-multi-thread"] }

[[bench]]
name = "benchmark"
harness = false
